apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: maxima-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio
          env:
            - name: MINIO_ROOT_USER
              value: "minio.admin"
            - name: MINIO_ROOT_PASSWORD
              value: "minio.admin"
          ports:
            - containerPort: 9000
            - containerPort: 9001
          args:
            - server
            - --console-address
            - ":9001"
            - /data
          volumeMounts:
            - name: minio-data
              mountPath: /data
      volumes:
        - name: minio-data
          persistentVolumeClaim:
            claimName: minio-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: maxima-admin
spec:
  selector:
    app: minio
  ports:
    - name: api-port # Имя для первого порта (API)
      protocol: TCP
      port: 9000
      targetPort: 9000
    - name: console-port # Имя для второго порта (консоль)
      protocol: TCP
      port: 9001
      targetPort: 9001
