apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-fpm
  namespace: maxima-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-fpm
  template:
    metadata:
      labels:
        app: php-fpm
    spec:
      containers:
        - name: php-fpm
          image: teleportkirov/maxima-admin-php
          workingDir: /app
          volumeMounts:
            - name: app-code
              mountPath: /app
      volumes:
        - name: app-code
          hostPath:
            path: /mnt/admin-panel
