apiVersion: v1
kind: PersistentVolume
metadata:
  name: laravel-code-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/admin-panel
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: laravel-code-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
